# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\"\x1b\n\x0eLetterResponse\x12\t\n\x01\x61\x18\x01 \x01(\t\"\x1a\n\rLetterRequest\x12\t\n\x01\x62\x18\x01 \x01(\t2F\n\x0bTestService\x12\x37\n\x10ServiceOneMethod\x12\x0e.LetterRequest\x1a\x0f.LetterResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LETTERRESPONSE']._serialized_start=14
  _globals['_LETTERRESPONSE']._serialized_end=41
  _globals['_LETTERREQUEST']._serialized_start=43
  _globals['_LETTERREQUEST']._serialized_end=69
  _globals['_TESTSERVICE']._serialized_start=71
  _globals['_TESTSERVICE']._serialized_end=141
# @@protoc_insertion_point(module_scope)
